### ISSUE TITLE
Speed control of the opposition to be considered.

### ISSUE THREAD

**Issue by swastkk** [ParthPant/chess-rs#1]
Addition of feature to control the speed of opposition should be included.
Since after playing 2-3 games, felt it was too quick since I was not able to see which move the opposition played.

**Comment by ParthPant** [comment]
That is a good idea. I added a Recent moves list at the bottom of the screen just to try and counter this. Having a little timeout before the opposition makes a move can make things even better. But it also would have to keep account of how much time the search took. we don't want to cause any additional delay that would make a slow search even slower.

**Comment by swastkk** [comment]
> That is a good idea. I added a Recent moves list at the bottom of the screen just to try and counter this. Having a little timeout before the opposition makes a move can make things even better. But it also would have to keep account of how much time the search took. we don't want to cause any additional delay that would make a slow search even slower.

Oh, I saw  that recent moves panel at the bottom now.
